# Sequential Team Approval Configuration
# This file defines the teams and their required approval order

# Teams must approve in the order listed below
teams:
  # Team 1 - First approval required
  - slug: your-team-slug-1  # GitHub team slug (required)
    name: Team Name 1       # Display name for the team
    description: First level approval - technical review
    slaHours: 24           # Expected response time in hours

  # Team 2 - Second approval required
  - slug: your-team-slug-2
    name: Team Name 2
    description: Second level approval - security review
    slaHours: 48

  # Team 3 - Final approval required
  - slug: your-team-slug-3
    name: Team Name 3
    description: Final approval - management sign-off
    slaHours: 72

# Workflow behavior options
options:
  # Automatically request review from the next team in sequence
  autoRequestReview: true
  
  # Update PR labels to show current approval status
  updateLabels: true
  
  # Post status comments on the PR
  postComments: true
  
  # Require all teams to approve (if false, allows partial approvals)
  requireAllTeams: true
  
  # Create labels if they don't exist in the repository
  createLabelsIfMissing: true
  
  # Enable SLA tracking and violations
  enableSLATracking: true
  
  # Send reminders for pending approvals
  sendReminders: true
  
  # How often to send reminders (in hours)
  reminderIntervalHours: 24
  
  # Skip draft PRs in scheduled checks
  skipDraftPRs: true
  
  # Send notifications when new approvals are detected
  notifyOnApproval: true

# Label colors (hex codes without #)
labelColors:
  pending: 'fbca04'    # yellow - for pending approval labels
  ready: '0e8a16'      # green - for "Ready to Merge" label
  blocked: 'd73a4a'    # red - for blocked/error states
  overdue: 'b60205'    # dark red - for SLA violations

# Custom messages
messages:
  allApproved: "🎉 All required teams have approved this PR in the correct order!"
  waitingApproval: "Waiting for approval from the next team in sequence."
  outOfOrder: "Teams must approve in the specified order. Please review the approval sequence."
